== For Developers

You are welcome to send us feature requests via our https://github.com/redpen-cc/redpen[GitHub page].

We also welcome development contributions.
Contributions in the form of pull requests are easy to integrate to the master branch.
If you are interested in joining the development team,
refer to the information below for details on how to set up a suitable RedPen development environment.

=== Preparation

To build RedPen, you must install the following tools:

* http://www.oracle.com/technetwork/java/javase/downloads/index.html[JDK]
* https://git-scm.com/book/en/v2/Getting-Started-Installing-Git[Git client]
* http://phantomjs.org/download.html[PhantomJS]

=== Development policy

Our development motto is "slowly but surely"!
This means that, sometimes, we cannot accept proposals containing drastic changes,
even if we can see that the proposal could be useful for the project.

=== Building RedPen

Build RedPen in Maven by executing the following command:

....
$./mvnw clean install
....

The built RedPen package is output to: `redpen/redpen-distribution/target`.
Unzip the package by executing the following command:

....
$ cd redpen/redpen-distribution/target
$ tar xvf redpen-distribution-*.*.*-SNAPSHOT-assembled.tar.gz
x redpen-distribution-*.*.*-SNAPSHOT/bin/
x redpen-distribution-*.*.*-SNAPSHOT/conf/
x redpen-distribution-*.*.*-SNAPSHOT/js/
x redpen-distribution-*.*.*-SNAPSHOT/js/test/
x redpen-distribution-*.*.*-SNAPSHOT/lib/
...
....

Your RedPen package is now ready to use.
The following is an example of how to use the redpen commands in the package:

....
$cd redpen-distribution-*.*.*-SNAPSHOT
$bin/redpen -h
usage: redpen-cli [Options] [<INPUT FILE>]
  -c,--conf <CONF FILE>                Configuration file (REQUIRED)
  -f,--format <FORMAT>                 Input file format
                                       (markdown,plain,wiki,asciidoc,latex)
  -h,--help                            Displays this help information and exits
  -l,--limit <LIMIT NUMBER>            error limit number
  -r,--result-format <RESULT FORMAT>   Output result format
                                       (json,json2,plain,plain2,xml)
  -v,--version                         Displays version information and exits
....

=== Testing

When you modify RedPen source files, be sure to add test cases
so that the reviewer can understand the expected behavior.
Before making a pull request, confirm that all test cases execute correctly.
The command for running RedPen test cases is as follows:

....
 ./mvnw test
....

=== Miscellaneous information

* Twitter account

https://twitter.com/redpen_news/

* Source repository (git)

https://github.com/redpen-cc/redpen

* Chat (Gitter)

https://gitter.im/redpen-cc/redpen

* Issue tracker

https://github.com/redpen-cc/redpen/issues

