[[formats]]
== RedPen Input Formats

RedPen supports the following types of input format:

- Plain Text
- Markdown
- AsciiDoc
- Wiki
- LaTeX
- Re:VIEW
- Java Properties
- reStructuredText

[[plain-text]]
=== Plain text

Plain text consists of a series of paragraphs. Paragraphs are separated by two
line breaks. For example, the following article has two paragraphs:

----
This is the first paragraph. This paragraph is the introduction of this article.
It introduces the central issue discussed throughout the rest of the article.

The second paragraph describes the details of the issue and attempts to present a solution.
----

[[asciidoc]]
=== AsciiDoc

See the http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[AsciiDoctor reference]

[[latex]]
=== LaTeX

NOTE: RedPen does not support macros defined by writers.

[[wiki-format]]
=== Wiki format

RedPen supports a subset of Wiki syntax. Currently, the supported
elements of Wiki syntax are as follows:

[[headings]]
==== Headings

To create a heading, add a line starting with **h[1234]**. The number after h represents the level of the heading or section.

[[inline-formatting]]
==== Inline Formatting

RedPen supports the following inline formatting:

[[bold]]
==== Bold

----
**This is a sentence in bold font.**
----

[[italic]]
==== Italic

----
//This is a sentence in italic font.//
----

[[underline]]
==== Underline

----
__This is an underlined sentence.__
----

[[strikethrough]]
==== Strikethrough

----
--This is a strikethrough sentence.--
----

[[links]]
==== Links

Link elements are included in Wiki formatted documents.

[[lists]]
==== Lists

Wiki syntax supports the following two types of list:

[[bulleted-lists]]
===== Bulleted Lists

To add a bulleted list, start each line with an asterisk. The number of
asterisks denotes the indent level of the list.

----
* List
* List
** Sub List
----

[[numbered-list]]
===== Numbered Lists

To add a numbered list, use the hash/pound symbol (#) instead
of the asterisk used for a bulleted list.

[[comments]]
==== Comments

To add a comment to the wiki source, add a ``[!-- ... --]`` block. The
following shows a sample comment:

----
[!--
  This is a comment.
--]
----

[[paragraphs]]
==== Paragraphs

Paragraphs are separated by two consecutive line breaks. This syntax is the same as
for plain text.

[[markdown]]
=== Markdown

RedPen currently supports the following Markdown elements:

[[headings-1]]
==== Headings

The following two styles of heading are supported:

* Underlined headings

You can specify first and second level headings by using underlines, as shown below.

----
First-level headings
====================
----

----
Second-level headings
---------------------
----

* Atx style headings

You can specify up to six levels of heading by adding 1-6 hash or pound characters (#) at the beginning of a line.

For example:

----
# First-level heading
## Second-level heading
### Third-level heading
----

[[inline-formatting-1]]
==== Inline Formatting

RedPen supports the following inline formatting:

[[bold-1]]
===== Bold

To display a sentence in bold font, enclose the sentence in double asterisks or double underscores. The
following are examples of sentences in bold font:

----
**This is a sentence in bold font.**
__This is also a sentence in bold font.__
----

[[italic-1]]
===== Italic

To display a sentence in bold font, enclose the sentence in single asterisks or single underscores. The
following are examples of sentences in italic font:

----
*This is a sentence in italic font.*
_This is also a sentence in italic font._
----

[[links-1]]
==== Links

To create a link, enclose the link text in square brackets and enclose
the URL in parentheses, as shown below.

----
[label](url)
----

[[lists-1]]
==== Lists

The Markdown parser used by RedPen supports two types of list:
Bulleted and Numbered.

[[bulleted-lists-1]]
===== Bulleted Lists

To add a bulleted list, start each line with an asterisk or a hyphen.
The lists are nested according to how many leading spaces there are. The
following is an example of a bulleted list using asterisks:

----
* List
* List
  * Sub List
  * Sub List
----

[[numbered-list-1]]
===== Numbered Lists

To add a numbered list, start each line with a number followed by a
period, as shown below.

----
1. List
2. List
----

[[paragraphs-1]]
==== Paragraphs

Paragraphs are separated by two consecutive line breaks. This syntax is the same as for plain text.

[[review-format]]
=== Re:VIEW format

For details, refer to the https://github.com/kmuto/review/blob/master/doc/format.md[Re:VIEW reference].

[[java-properties]]
=== Java Properties

Properties files or Resource Bundles are commonly used for internalization in Java.
RedPen treats each property as a section, which can have one or more sentences. Comments and values are validated, but keys are not.

For details on file format, refer to the https://docs.oracle.com/javase/7/docs/api/java/util/Properties.html#load(java.io.Reader)[Properties Javadoc].

[[restuucturedtext]]
=== reStructuredText

NOTE: Currently, RedPen only supports basic notations.

For details, refer to the http://docutils.sourceforge.net/docs/user/rst/quickstart.html#structure[ReStructuredText Primer].
