[[redpen-output-format]]
== RedPen Output Formats

RedPen supports three basic output formats - **Plain text**, **XML**, and **JSON**.

NOTE: From v1.10, RedPen supports2 error level (default is *error*). For the configuration, please refer to the <<validator-configuration, Validator configuration>> section.

[[plain-text]]
=== Plain text

Plain text output format consists of the following lines.

----
FILE_NAME:LINE_NUM: Validation[Error|Info|Warn][ERROR_TYPE], ERROR_MESSAGE at line: SENTENCE
----

An alternate plain text form (plain2) prints each sentence, followed by
all of the errors found in the sentence.

[[xml]]
=== XML

The top section of the XML output format is *validation-result* element
which contains multiple *error* sections. Each error section has the
following sub-elements.

[option="header"]
|====
|Block             |   Optional  |    Description
|`validator`       |   false     |    Validator name
|`message`         |   false     |    Error message
|`lineNum`         |   false     |    Line Number
|`sentence`        |   false     |    Sentence containing error
|`file`            |   true      |    File name
|`level`           |   String    |    Error level (info, warn, error)
|====

[[json]]
[suppress='UnexpandedAcronym']
=== JSON

[option="header"]
|====
|Block             |   Optional   |   Description
|`validator`       |   false      |   Validator name
|`message`         |   false      |   Error message
|`lineNum`         |   false      |   Line Number
|`sentence`        |   false      |   Sentence containing error
|`file`            |   true       |   File name
|`level`           |   String    |    Error level (info, warn, error)
|====

The alternative JSON output format (json2) collates each error by the
sentence it relates to.
