[[suppress-section]]
[suppress='CommaNumber']
== Error Suppression

Sometimes writers do not want to fix errors from RedPen.
The reason is the cost to remove error is high or writer intend to break the writing standard at particular points.
For such cases, RedPen support **error suppression by annotation**. The annotations are added just before the section containing the errors.
Currently error suppression is supported for four types of formats (AsciiDoc, Markdown, Re:VIEW, LaTeX).

=== AsciiDoc

For AsciiDoc text, writers add the suppress annotation in attribute block. The annotation is **[suppress]**. For example, the following AsciiDoc text suppresses the all the erorrs in the section.

```
[suppress]
= Instances
Some software tools work in more than one machine, and such distributed (cluster)systems can handle huge data or tasks, because such software tools make use of large amount of computer resources, such as CPU, Disk, and Memory.
```

When the writers want to suppress only the specified errors, they add Validator names after **suppress**. For example, the following example suppresses only two types of errors (Contraction WeakExpression).

```
[suppress='Contraction WeakExpression']
= Instances
Some software tools work in more than one machine, and such distributed (cluster)systems can handle huge data or tasks, because such software tools make use of large amount of computer resources, such as CPU, Disk and Memory.
```

NOTE: Multi line section is not supported for suppression error with annotation.

=== Markdown

For Markdown text, writers add the suppress annotation in HTML comments. Specifically Writers add annotation, **@suppress** in HTML comments.
For example, the following text suppress all the error in the section.

```
<!-- @suppress -->
# Instances
Some software tools work in more than one machine, and such _distributed_ (cluster)systems can handle huge data or tasks, because such software tools make use of large amount of computer resources, such as CPU, Disk and Memory.
```

To suppress only specific errors, writers add the Validator names following @suppress annotation. The following sample suppresses the two type errors (Contraction WeakExpression).

```
<!-- @suppress Contraction WeakExpression -->
# Instances
Some software tools work in more than one machine, and such _distributed_ (cluster)systems can handle huge data or tasks, because such software tools make use of large amount of computer resources, such as CPU, Disk and Memory.
```

NOTE: Multi line comments style is not supported.

=== Re:VIEW

For Re:VIEW text, writers add the suppress annotation in comments. Specifically Writers add annotation, **@suppress** in Re:VIEW comment **\#@#**.
For example, the following text suppress all the error in the section.

```
#@# @suppress
= Instances
Some software tools work in more than one machine, and such distributed (cluster)systems can handle huge data or tasks, because such software tools make use of large amount of computer resources, such as CPU, Disk and Memory.
```

To suppress only specific errors, writers add the Validator names following @suppress annotation. The following sample suppresses the two type errors (Contraction WeakExpression).

```
#@# @suppress Contraction WeakExpression
= Instances
Some software tools work in more than one machine, and such distributed (cluster)systems can handle huge data or tasks, because such software tools make use of large amount of computer resources, such as CPU, Disk and Memory.
```

=== LaTeX

For LaTeX texts, writers can add Markdown style annotation in LaTeX comment (%).
