[[suppress-section]]
[suppress='CommaNumber']
== Error Suppression

In some cases, you may not want to fix errors pointed out by RedPen.
For example, if the cost of removing the errors is high,
or if you intentionally want to ignore a particular writing standard at particular point.
For such cases, RedPen provides a function for **suppressing errors by annotation**.
You add the annotation immediately before the section containing the errors that you want to ignore.
You can suppress errors in files in AsciiDoc, Markdown, Re:VIEW or LaTeX format,
as described below.

=== AsciiDoc

For files in AsciiDoc format, you add the suppress annotation in an attribute block. The annotation is **[suppress]**.
In the example below, all errors in the "Instances" section are suppressed.

```
[suppress]
= Instances
Some software tools work in more than one machine, and such distributed (cluster) systems can handle huge data or tasks, because such software tools make use of large amounts of computer resources, such as CPU, Disk, and Memory.
```

If you want to suppress only specific types of error, add the relevant validator names after **suppress**.
In the example below, two types of error are suppressed (Contraction and WeakExpression).

```
[suppress='Contraction WeakExpression']
= Instances
Some software tools work in more than one machine, and such distributed (cluster) systems can handle huge data or tasks, because such software tools make use of large amounts of computer resources, such as CPU, Disk and Memory.
```

NOTE: Multi-line comments are not allowed.

=== Markdown

For files in Markdown format, you add the suppress annotation in an HTML comment. The annotation is **@suppress**.
In the example below, all errors in the "Instances" section are suppressed.

```
<!-- @suppress -->
# Instances
Some software tools work in more than one machine, and such distributed (cluster) systems can handle huge data or tasks, because such software tools make use of large amounts of computer resources, such as CPU, Disk and Memory.
```

If you want to suppress only specific types of error, add the relevant validator names after **@suppress**.
In the example below, two types of error are suppressed (Contraction and WeakExpression).

```
<!-- @suppress Contraction WeakExpression -->
# Instances
Some software tools work in more than one machine, and such distributed (cluster) systems can handle huge data or tasks, because such software tools make use of large amounts of computer resources, such as CPU, Disk and Memory.
```

NOTE: Multi-line comments are not allowed.

=== Re:VIEW

For files in Re:VIEW format, you add the suppress annotation in a Re:VIEW comment. The annotation is **@suppress**.
In the example below, all errors in the "Instances" section are suppressed.

```
#@# @suppress
= Instances
Some software tools work in more than one machine, and such distributed (cluster) systems can handle huge data or tasks, because such software tools make use of large amounts of computer resources, such as CPU, Disk and Memory.
```

To suppress only specific errors, writers add the Validator names following @suppress annotation. In the example below, two types of error are suppressed (Contraction and WeakExpression).

```
#@# @suppress Contraction WeakExpression
= Instances
Some software tools work in more than one machine, and such distributed (cluster) systems can handle huge data or tasks, because such software tools make use of large amount of computer resources, such as CPU, Disk and Memory.
```

=== LaTeX

For files in LaTeX format, you add Markdown style annotation in LaTeX comments (%).


=== reStructuredText

For files in reStructuredText format, you add the suppress annotation in inline comments as shown below.

```
.. @suppress Contraction WeakExpression

Distributed system
##################

Some software tools work in more than one machine, and such distributed (cluster) systems can handle huge data or tasks, because such software tools make use of large amounts of computer resources, such as CPU, Disk and Memory.
```


