[[validator]]
== RedPen Validators

This section describes the validators provided by RedPen.

[[commanumber]]
=== CommaNumber

CommaNumber checks the number of commas in a sentence.
If a sentence contains more than the maximum number of commas,
the validator generates a warning.

[[properties-3]]
==== Properties

[options="header"]
|====
|Property        |Default Value  |Description
|``max_num``     |3              |The maximum number of commas allowed in a sentence.
|====

[[supported-languages-1]]
==== Supported languages

CommaNumber can be applied to any language.


[[contraction]]
=== Contraction

Contraction checks for contractions in a document.
If more than half of the verbs are written in non-contracted form,
the validator generates a warning when it finds a contraction.

[[supported-languages-8]]
==== Supported languages

Contraction can only be applied to English documents.


[[doubled-conjunctive-particle-ga]]
=== DoubledConjunctiveParticleGa

DoubledConjunctiveParticleGa checks if the Japanese conjunction *ga (が)* is used
twice in the same sentence. For example, if the document contains the sentence below,
the validator generates a warning because *ga* is used twice.

----
今日は早朝から出発したが、定刻通りではなかったが、無事会場に到着した。 
----


[[supported-languages-doubled-conjunctive-particle-ga]]
==== Supported languages

DoubledConjunctiveParticleGa can only be applied to Japanese documents.


[[doubledjoshi]]
=== DoubledJoshi

DoubledJoshi checks if the same joshi (a Japanese part-of-speech for linking
words and phrases) is used more than once in a Japanese sentence.

You can add joshi that you do not want to be flagged as doubled by creating a
dictionary or word list. The dictionary is a file in dat or txt format that
contains one joshi per line.

[[properties-doubled-joshi]]
==== Properties

[options="header"]
|====
|Property        |Default Value  |Description
|``dict``        |None           |The file name of the dictionary.
|``list``        |None           |A list of words to skip delimited by commas.
|====

[[supported-languages-doubled-joshi]]
==== Supported languages

DoubledJoshi can only be applied to Japanese documents.


[[doubledword]]
=== DoubledWord

DoubledWord checks if a word is used more than once in the same sentence.
For example, if the document contains the following sentence, the validator
generates a warning because *good* is used twice.

----
This good item is very good.
----

You can add words that you do not want to be flagged as doubled words by
creating a dictionary or word list. The dictionary is a file in dat or txt
format that contains one word per line.

[[properties-8]]
==== Properties

[options="header"]
|====
|Property        |Default Value  |Description
|``dict``        |None           |The file name of the dictionary.
|``list``        |None           |A list of words to skip delimited by commas.
|====

[[supported-languages-10]]
==== Supported languages

DoubledWord can be applied to Japanese and any language that uses a space to
separate words. It cannot be applied to Chinese or other Asian languages.

NOTE: Default dictionaries are provided only for English and Japanese.


[[doublenegative]]
=== DoubleNegative

DoubleNegative checks if the document contains any double negative expressions.

[[supported-languages-14]]
==== Supported languages

DoubleNegative can only be applied to English and Japanese documents.


[[duplicatedsection]]
=== DuplicatedSection

DuplicatedSection checks if the document contains sections that are identical
or similar.

NOTE: Because RedPen treats a text file as a single section, DuplicatedSection does not work with text files.

[[supported-languages-12]]
==== Supported languages

DuplicatedSection can be applied to any language.


[[emptysection]]
=== EmptySection

EmptySection checks if any sections in the document do not contain any
paragraphs or sentences.

[[properties-emptysection]]
==== Properties

[options="header"]
|====
|Property        |Default Value  |Description
|``limit``       |5              |The hierarchical level at which to skip validating sections (with "1" being the top level of the document).
|====

NOTE: EmptySection does not work in files in text format (.txt).

[[supported-languages-emptysection]]
==== Supported languages

EmptySection can be applied to any language.


[[endofsentence]]
=== EndOfSentence

EndOfSentence checks if the document contains any sentences that do not follow
the American style of placing sentence ending punctuation marks inside
quotation marks.

[[supported-languages-end-of-sentence]]
==== Supported languages

EndOfSentence can only be applied to English documents.


[[frequentsentencestart]]
=== FrequentSentenceStart

FrequentSentenceStart checks if too many sentences start with the same
sequence of words.

==== Properties

[options="header"]
|====
|Property        |Default Value  |Description
|``leading_word_limit``      |3              |The number of words to consider at the start of each sentence.
|``percentage_threshold``    |25             |The maximum percentage of sentences that can start with the same words.
|``min_sentence_count``      |5              |The minimum number of sentences required in the document for the validator to report errors.
|====

[[supported-languages-15]]
==== Supported languages

FrequentSentenceStart can be applied to Japanese and any language that uses a
space to separate words. It cannot be applied to Chinese or other Asian
languages.


[[gappedsection]]
=== GappedSection

GappedSection checks if there is a chapter, section or subsection missing in
the logical structure of the document. For example, in the example below, the
validator generates a warning because Section 1.1 is expected between
Chapter 1 and Subsection 1.1.1.

----
= Chapter 1
...
=== Subsection 1.1.1
=== Subsection 1.1.2
...
----

NOTE: GappedSection does not work in files in text format (.txt).

[[supported-languages-gappedsection]]
==== Supported languages

GappedSection can be applied to any language.


[[HankakuKana]]
=== HankakuKana

HanakakuKana checks if the document contains any single-byte katakana
characters (also called “half-width kana”).

[[supported-languages-hankaku-kana]]
==== Supported languages

HanakakuKana can only be applied to Japanese documents.


[[hyphenation]]
[suppress='WeakExpression']
=== Hyphenation

Hyphenation checks that words in the document are hyphenated according to
dictionary usage.

[[supported-languages-18]]
==== Supported languages

Hyphenation can only be applied to English documents.


[[invalidexpression]]
=== InvalidExpression

InvalidExpression checks if the input document contains any invalid
words or phrases listed in a pre-defined dictionary. If the input document
contains an invalid expression, the validator generates a warning.

[[properties-1]]
==== Properties

[options="header"]
|====
|Property        |Default Value  |Description
|``dict``        |None           |The file name of the dictionary.
|``list``        |None           |A list of invalid expressions delimited by commas.
|====

You can add expressions by adding a dictionary or word list.
A dictionary is a file in dat or txt format that contains one expression per line.
The following is an example of a dictionary listing:

----
like
you know
hey
kidding
...
----

[[supported-languages-1]]
==== Supported languages

InvalidExpression can be applied to any language.


[[invalidsymbol]]
[suppress='InvalidSymbol WeakExpression']
=== InvalidSymbol

Some symbols or characters have more than one representation.
For example, the standard question mark in Unicode is **? (0x003F)**,
but **？(0xFF1F)** also exists. InvalidSymbol checks if the input document
contains any invalid characters or symbols. You can specify invalid
symbols in the symbols block in the configuration file. For more details,
refer to <<setting-symbols>>.

[[supported-languages-2]]
==== Supported languages

InvalidSymbol can be applied to any language.


[[invalidword]]
=== InvalidWord

InvalidWord checks if the input document contains any invalid
words listed in a pre-defined dictionary. If the input document
contains an invalid word, the validator generates a warning.

[[properties-2]]
==== Properties

[options="header"]
|====
|Property        |Default Value  |Description
|``dict``        |None           |The file name of the dictionary.
|``list``        |None           |A list of invalid expressions delimited by commas.
|====

You can add words by adding a dictionary or word list.
A dictionary is a file in dat or txt format that contains one word per line.
The following is an example of a dictionary listing:

----
like
hey
wow
...
----

[[supported-languages]]
==== Supported Languages

InvalidWord can be applied to any language that separates words using spaces
(such as English or French).
A default dictionary is supplied for English.


[[japanese-ambiguous-noun-conjunction]]
[suppress='WeakExpression']
=== JapaneseAmbiguousNounConjunction

JapaneseAmbiguousNounConjunction checks if the document contains an ambiguous
noun conjunction pattern. The pattern is defined as a string of noun phrases
joined by two or more instances of the conjunction **no (の)**, as shown in the example below.

----
弊社の経営方針の説明を受けた。
----

[[properties-japanese-ambiguous-noun-conjunction]]
==== Properties

[options="header"]
|====
|Property        |Default Value  |Description
|``dict``        |None           |The file name of the dictionary containing expressions to ignore.
|``list``        |None           |A list of expressions to ignore, delimited by commas.
|====
[[supported-language-japanese-ambiguous-noun-conjunction]]
==== Supported languages

JapaneseAmbiguousNounConjunction can only be applied to Japanese documents.

[[japanese-anchor-expression]]
=== JapaneseAnchorExpression

JapaneseAnchorExpression checks that chapters and sections are marked in a
consistent style.

[[properties-japanese-anchor-expression]]
==== Properties

[options="header"]
|====
|Property        |Default Value  |Description
|``mode``        |numeric        |The permitted style of anchor expression. This must be one of the following: "numeric", "numeric-zenkaku" or "kansuji".
|====

The details of these styles are as follows:

[options="header"]
|====
|Style                | Sample
|``numeric``          | 1章、2節 (single-byte number with kanji for chapter or section)
|``numeric-zenkaku``  | １章、２節 (double-byte number with kanji for chapter or section)
|``kansuji``          | 一章、二節 (kanji number with kanji for chapter or section)
|====

NOTE: RedPen ignores the style if the number follows the kanji for chapter or section (for example, 章1).

[[supported-language-japanese-anchor-expression]]
==== Supported languages

JapaneseAnchorExpression can only be applied to Japanese documents.


[[japanese-expression-variation]]
=== JapaneseExpressionVariation

JapaneseExpressionVariation checks for variations in the use of expressions
in Japanese documents.
The function of JapaneseExpressionVariation is similar to KatakanaSpellCheck,
but whereas KatakanaSpellCheck only checks katakana,
JapaneseExpressionVariation also checks hiragana and kanji. For example,
you can check if a word is written in kanji and hiragana in the same document.
You can prepare a dictionary or list of expressions to specifically check for.

[[properties-japanese-expression-variation]]
==== Properties

[options="header"]
|====
|Property        |Default Value  |Description
|``dict``        |None           |The file name of the dictionary.
|``map``         |None           |A list of pairs of expressions. For example: `{smart,スマート},{distributed,ディストリビューテッド}`
|====

The dictionary is a tab-separated value (TSV) file in dat format consisting of
two columns. Each column contains one of the pair of expressions that you
want to check for.
The following is an example of a dictionary listing:

----
SVM    Support Vector Machine
LLVM   Low Level Virtual Machine
...
----

[[supported-language-japanese-expression-variation]]
==== Supported languages

JapaneseExpressionVariation can only be applied to Japanese documents.


[[japanese-joyo-kanji]]
=== JapaneseJoyoKanji

JapaneseJoyoKanji checks if the document contains any kanji that are not
included in the official "joyo kanji" list, such as the following:

----
殆 (hotondo), 踵 (kakato), 迄 (made)
----

[[supported-language-japanese-joyo-kanji]]
==== Supported languages

JapaneseJoyoKanji can only be applied to Japanese documents.


[[japanese-number-expression]]
=== JapaneseNumberExpression

JapaneseNumberExpression checks if the number expressions ending in "tsu"
that are used in the document are consistent in style.

[[properties-section-level]]
==== Properties

[options="header"]
|====
|Property        |Default Value  |Description
|``mode``        |numeric        |The permitted style of number expression. This must be one of the following: "numeric", "numeric-zenkaku", "kansuji", "hiragana".
|====

The details of these styles are as follows:

[options="header"]
|====
|Style                | Sample
|``numeric``          | 1つ、2つ (single-byte number with hiragana "tsu")
|``numeric-zenkaku``  | １つ、２つ (double-byte number with hiragana "tsu")
|``kansuji``          | 一つ、二つ (kanji number with hiragana "tsu")
|``hiragana``         | ひとつ、ふたつ (all hiragana)
|====

[[supported-language-japanese-number-expression]]
==== Supported languages

JapaneseNumberExpression can only be applied to Japanese documents.


[[japanesestyle]]
=== JapaneseStyle

JapaneseStyle checks if the input document contains both the "de-aru"
and "desu-masu" styles.

[[supported-languages-13]]
==== Supported languages

JapaneseStyle can only be applied to Japanese documents.


[[javascript]]
=== JavaScript

JavaScript executes any additional validators that you create in JavaScript.
For details on creating validators in JavaScript, refer to <<extending-with-javascript>>.

[[properties-javascript]]
==== Properties

[options="header"]
|====
|Property        |Default Value  |Description
|``script_path``   |$REDPEN_HOME/js              |The directory that contains the JavaScript files. You can set multiple ``script_path`` properties.
|====

[[supported-languages-javascript]]
==== Supported languages

JavaScript can be applied to any language.


[[katakanaendhyphen]]
[suppress='InvalidSymbol NumberFormat WeakExpression']
=== KatakanaEndHyphen

KatakanaEndHyphen checks that the long vowel symbol ("end hyphen") at the end
of katakana words in *Japanese* documents is used according to the standard
JIS Z8301, G.6.2.2 b) G.3. For example, "computer" can be written in katakana
as "コンピュータ" (without end hyphen), and "コンピューター" (with end hyphen).
However, according to JIS Z8301, "コンピュータ" is correct. If the input
document contains "コンピューター", the validator generates a warning.

The basic rules of JIS Z8301 are as follows:

* a: Words of 3 characters or more cannot have an end hyphen.
* b: Words of 2 characters or less must have an end hyphen.
* c: A compound word should apply *a* and *b* to each component word.
* d: When counting characters for cases *a* to *c* above, the following
characters are counted:
“―”: Long vowel symbol, as in “テーパ” (taper)
“ン”: “n” sound, as in “ダンパ” (dumper)
“ッ”: Small “tsu”, as in “ニッパ” (nipper)
And the following characters are not counted:
Diphthong characters such as “ャ” in “シャワー” (shower)

==== Properties

[options="header"]
|====
|Property        |Default Value  |Description
|``list``        |None           |A comma-separated list of words with end hyphens that should not be flagged by KatakanaEndHyphen.
|====

[[supported-languages-4]]
==== Supported languages

KatakanaEndHyphen can only be applied to Japanese documents.


[[katakanaspellcheck]]
=== KatakanaSpellCheck

KatakanaSpellCheck checks for similar katakana words in the same Japanese
document that might be the result of misspelling. For example, depending on
the *min_ratio* setting, if "パラメタ" and the similar "パラメータ" exist in
the same document, the validator generates a warning.

==== Properties

[options="header"]
|====
|Property        |Default Value  |Description
|``dict``        |None           |The file name of the dictionary.
|``min_ratio``   |0.3            |The degree of similarity between words for KatakanaSpellCheck to check. The valid range is from 0.1 to 0.9. The smaller the value, the more the words must match.
|``min_freq``    |5              |The maximum number of times a word can occur in the document for KatakanaSpellCheck to check. If a word occurs more times than the specified value, it is not checked.
|====

[[supported-languages-5]]
==== Supported languages

KatakanaSpellCheck can only be applied to Japanese documents.


[[list-level]]
=== ListLevel

ListLevel checks how deeply lists are nested. This validator generates a
warning if a list has more levels than the value specified for  ``max_level ``.

NOTE: ListLevel does not work in files in text format (.txt).

[[properties-list-level]]
==== Properties

[options="header"]
|====
|Property        |Default Value  |Description
|``max_level``   |5              |The maximum number of levels allowed in a list.
|====

For example, if  ``max_level`` is set to 5, the validator generates a warning
for the list below because it has six levels.

----
* one
** two
*** three
**** four
***** five
****** six
----

[[supported-languages-list-level]]
==== Supported languages

ListLevel can be applied to any language.


[[long-kanji-chain]]
=== LongKanjiChain

LongKanjiChain checks if the document contains long strings of kanji
characters. If a string is longer than the specified maximum length,
the validator generates a warning.


[[properties-long-kanji-chain]]
==== Properties

[options="header"]
|====
|Property        |Default Value  |Description
|``max_len``  |5  |The maximum number of kanji characters allowed in succession.
|====

[[supported-language-long-kanji-chain]]
==== Supported languages

LongKanjiChain can only be applied to Japanese documents.


[[numberformat]]
[suppress='WeakExpression NumberFormat SymbolWithSpace']
=== NumberFormat

NumberFormat checks that numbers in a document are delimited in three-digit
blocks using commas (for example, “12,000” instead of “12000”).
It also checks which symbol is used to delimit three-digit blocks and which
symbol is used as to denote a decimal point.

[[properties-11]]
==== Properties

[options="header"]
|====
|Property        |Default Value  |Description
|``decimal_delimiter_is_comma``  |  false          |If false, the validator assumes that the decimal point is a period (".").
If true, the validator assumes that the decimal point is a comma (","), as used in most European countries.

|``ignore_years``                |  true           |If false, the validator assumes that all integers are numbers and checks accordingly for commas or periods. If true, the validator assumes that 4-digit integers (such as 2015 and 1998) are years and does not check them for commas or periods.

|====

[[supported-languages-19]]
==== Supported languages

NumberFormat can be applied to documents written in European languages such
as English or French.


[[okurigana]]
=== Okurigana

Okurigana checks if the document contains any incorrect okurigana
(declensional kana endings for kanji used in Japanese).

[[supported-languages-okurigana]]
==== Supported languages

Okurigana can only be applied to Japanese documents.


[[paragraphnumber]]
=== ParagraphNumber

ParagraphNumber checks the number of paragraphs in a section.
If the number is greater than the specified maximum number,
the validator generates a warning.

NOTE: RedPen treats a text file as a single section.

[[properties]]
==== Properties

[options="header"]
|====
|Property        |Default Value  |Description
|``max_num``     |5           |The maximum number of paragraphs allowed in a section.
|====

[[supported-languages-1]]
==== Supported languages

ParagraphNumber can be applied to any language.


[[paragraphstartwith]]
=== ParagraphStartWith

ParagraphStartWith checks that paragraphs do not start with illegal characters.

[[properties-7]]
==== Properties

[options="header"]
|====
|Property        |Default Value  |Description
|``start_with``  |" "            |The character that cannot appear at the start of a paragraph.
|====

[[supported-languages-6]]
==== Supported languages

ParagraphStartWith can be applied to any language.


[[parenthesizedsentence]]
=== ParenthesizedSentence

ParenthesizedSentence checks if parenthesized phrases (such as this) are used
too frequently, are nested too deeply, or are too long.

[[properties-12]]
==== Properties

[options="header"]
|====
|Property        |Default Value  |Description
|``max_nesting_level``  |2  |The maximum level to which parenthesized phrases may be nested (one parenthesized phrase inside another (such as this)).
|``max_count``          |1  |The maximum number of parenthesized phrases allowed in a sentence.
|``max_length``         |4  |The maximum number of words allowed in a parenthesized phrase.
|====

[[supported-languages-20]]
==== Supported languages

ParenthesizedSentence can be applied to any language.


[[sectionlength]]
=== SectionLength

SectionLength checks the number of characters (letters, numbers and symbols)
in a section. If the number is greater than the specified maximum number,
the validator generates a warning.

NOTE: RedPen treats a text file as a single section.


[[properties-6]]
==== Properties

[options="header"]
|====
|Property        |Default Value  |Description
|``max_num``     |1000           |The maximum number of characters allowed in a section.
|====

[[supported-languages]]
==== Supported languages

SectionLength can be applied to any language.


[[section-level]]
=== SectionLevel

SectionLevel checks the number of levels in the section hierarchy.
If the document contains more levels than the specified maximum number,
the validator generates a warning.

[[properties-section-level]]
==== Properties

[options="header"]
|====
|Property        |Default Value  |Description
|``max_num``     |5              |The maximum number of levels allowed.
|====

[[supported-language-section-level]]
==== Supported languages

SectionLevel can be applied to any language.


[[sentencelength]]
=== SentenceLength

SentenceLength checks the length of sentences in the input
document. If the length of a sentence is greater than the specified
maximum length, the validator generates a warning.

[[properties]]
==== Properties

[options="header"]
|====
|Property        |Default Value  |Description
|``max_len``     |120            |The maximum length of a sentence (in characters).
|====

[[supported-languages]]
==== Supported languages

SentenceLength can be applied to any language.


[[spacebeginningofsentence]]
=== SpaceBeginningOfSentence

SpaceBeginningOfSentence checks if there is a space between any two adjacent sentences
(except for the last sentence of paragraph). If there is not, the validator generates a warning.

WARNING: SpaceBeginningOfSentence is now deprecated.

[[supported-languages-2]]
==== Supported languages

SpaceBeginningOfSentence can be applied to any language.


[[spacebetweenalphabeticalword]]
[suppress='WeakExpression']
=== SpaceBetweenAlphabeticalWord

SpaceBetweenAlphabeticalWord checks that a single-byte alphabetic word that
appears in a double-byte language document (such as Japanese or Chinese)
is preceded and followed by a single-byte space.

[[properties-spacebetweenalphabeticalword]]
==== Properties

[options="header"]
|====
|Property        |Default Value  |Description
|``forbidden``   | false         | If false, spaces are required. If true, spaces are not allowed.
|``skip_before`` | ""            | Ignores cases where there is no space AFTER the specified character.
|``skip_after``  | ""            | Ignores cases where there is no space BEFORE the specified character.
|====

[[supported-languages-spacebetweenalphabeticalword]]
==== Supported languages

SpaceBetweenAlphabeticalWord can be applied to any language that does not
use spaces to separate words, such as Japanese or Chinese.


[[spelling]]
=== Spelling

Spelling checks for spelling mistakes in a document.
You can add words that you do not want to be flagged as spelling mistakes
(such as product names) by creating a dictionary or word list.
The dictionary is a file in dat or txt format that contains one word per line.

[[properties-spelling]]
==== Properties

[options="header"]
|====
|Property        |Default Value  |Description
|``dict``        |None           |The file name of the dictionary.
|``list``        |None           |A list of words to skip delimited by commas.
|====

[[supported-languages-9]]
==== Supported languages

Spelling can only be applied to English documents.


[[startwithcapitalcharacter]]
=== StartWithCapitalLetter

StartWithCapitalLetter checks if sentences start with a capital character.

[[supported-languages-startwithcapitalcharacter]]
==== Supported languages

StartWithCapitalLetter can be applied to documents written in European
languages such as English or French.


[[successive-sentence]]
=== SuccessiveSentence

SuccessiveSentence checks if the document contains two or more sentences in
succession which are identical or almost identical. For example, if the
document contains the paragraph below, the validator generates a warning
because the same sentence is used twice in succession.

----
The component is useful for testing. Especially for unit level testing. Especially for unit level testing. If necessary, we can apply it for higher level testing.
----


[[properties-successive-sentence]]
==== Properties

[options="header"]
|====
|Property        |Default Value  |Description
|``dist``        |3              |The degree of similarity between sentences. If the value of "dist" is 0, the sentences must be identical in order for the validator to generate a warning.
|``min_len``     |5              |The minimum number of words a sentence must contain in order to be checked.
|====

[[supported-language-successive-sentence]]
==== Supported languages

SuccessiveSentence can be applied to any language.


[[successiveword]]
[suppress="SuccessiveWord"]
=== SuccessiveWord

SuccessiveWord checks if the same word is used twice in succession.
For example, if the document contains the sentence below,
the validator generates a warning because *is* is used twice in succession.

----
The item is is very good. 
----

[[supported-languages-11]]
==== Supported languages

SuccessiveWord can be applied to Japanese and any language that uses a space
to separate words. It cannot be applied to Chinese or other Asian languages.


[[suggestexpression]]
=== SuggestExpression

SuggestExpression works in a similar way to InvalidExpression.
If the input document contains an invalid expression,
the validator generates a warning and suggests an alternative expression.

[[properties-5]]
==== Properties

[options="header"]
|====
|Property        |Default Value  |Description
|``dict``        |None           |The file name of the dictionary.
|``map``         |None           |A list of pairs of expressions. Each pair consists of an invalid expression separated by a comma from its suggested replacement. For example: `{SVM,Support Vector Machine},{like,such as}`
|====

The dictionary is a tab-separated value (TSV) file in dat format consisting of
two columns. The first column contains the invalid expression, and the second
column contains a suggested replacement expression.
The following is an example of a dictionary listing:

----
SVM    Support Vector Machine
LLVM   Low Level Virtual Machine
...
----

[[supported-languages-4]]
==== Supported languages

SuggestExpression can be applied to any language.
Default dictionaries are provided for English and Japanese.


[[symbolwithspace]]
[suppress='WeakExpression']
=== SymbolWithSpace

SymbolWithSpace checks if symbols are preceded or followed by a space,
as appropriate. You can specify which symbols must (or must not) be preceded
or followed by a space in the *symbols*  block in the configuration file.
For more details, refer to <<setting-symbols>>.

[[supported-languages-3]]
==== Supported languages

SymbolWithSpace can be applied to any language.


[[unexpandedacronym]]
[suppress='WeakExpression']
=== UnexpandedAcronym

UnexpandedAcronym checks that, if an acronym appears in a document, the
expanded version of the acronym also appears somewhere in the document.

For example, if there exists an acronym ABC in the document, then there must also
exist a sequence of capitalized words such as Axxx Bxx Cxxx.

[[properties-9]]
==== Properties

[options="header"]
|====
|Property        |Default Value  |Description
|``min_acronym_length``    |3             |The minimum length of acronyms to check.
|====

[[supported-languages-16]]
==== Supported languages 

UnexpandedAcronym can only be applied to English documents.


[[voidsection]]
=== VoidSection

VoidSection checks if any sections in the document do not contain any
paragraphs or sentences.

WARNING: VoidSection is deprecated and will be removed in a future release.
Use EmptySection instead. 

[[properties-voidsection]]
==== Properties

[options="header"]
|====
|Property        |Default Value  |Description
|``limit``       |5              |The hierarchical level at which to skip validating sections (with "1" being the top level of the document).
|====

[[supported-languages-voidsection]]
==== Supported languages

VoidSection can be applied to any language.


[[weakexpression]]
=== WeakExpression

WeakExpression checks if the document contains any words or phrases listed in
a pre-defined dictionary of weak expressions.

[[supported-languages-21]]
==== Supported languages

WeakExpression can only be applied to English documents.


[[wordfrequency]]
[suppress='WeakExpression']
=== WordFrequency

WordFrequency checks that certain words do not appear too frequently in a
document. The validator generates a warning if a word appears too often with
reference to a histogram of word frequency for written English.

[[properties-10]]
==== Properties

[options="header"]
|====
|Property        |Default Value  |Description
|``deviation_factor``   |      3       |      The permitted factor of deviation from the norm. This means that, if a word is normally used 3% of the time, your document can use it up to 9% of the time.
|``min_word_count``     |      200     |      The minimum number of words in a document required for this validator to activate.
|====

[[supported-languages-17]]
==== Supported languages

WordFrequency can only be applied to English documents.


[[wordnumber]]
=== WordNumber

WordNumber checks the number of words in a sentence.
If a sentence contains more than the maximum number of words,
the validator generates a warning.

[[properties-4]]
==== Properties

[options="header"]
|====
|Property        |Default Value  |Description
|``max_num``     |30             |The maximum number of words allowed in a sentence.
|====

[[supported-languages-3]]
==== Supported languages

WordNumber can be applied to any language that separates words
using spaces (such as English or French).
