== Development RedPen

Feature requests are warm welcome through the GitHub. If you are interested in joining the development team.
The following instructions help you to understand building RedPen development environment. Contributions
in the form of pull requests are easy to integrate to the master branch.

=== Preliminary

To build RedPen, you need to install the following tools.

* http://www.oracle.com/technetwork/java/javase/downloads/index.html[JDK]
* https://git-scm.com/book/en/v2/Getting-Started-Installing-Git[Git client]
* http://www.dowdandassociates.com/blog/content/howto-install-maven/[Maven (v3 or later)]
* http://phantomjs.org/download.html[PhantomJS]

=== Development Policy

We will develop this tiny tool slow but steady. Therefore We would not be able to accept drastic changes,
even when the proposed change gives us the gain. This policy is needed us to enjoy writing and coding in
our daily life.

=== Build RedPen

Building all the RedPen package is simple. You just run the following command.

....
$ mvn install
....

The built RedPen package is output in `redpen/redpen-distribution/target/redpen-distribution-*.*.*-SNAPSHOT-assembled.tar.gz`.
After you get the built RedPen package, you unzip it with the following command.

....
$ cd redpen/redpen-distribution/target
$ tar xvf redpen-distribution-*.*.*-SNAPSHOT-assembled.tar.gz
x redpen-distribution-*.*.*-SNAPSHOT/bin/
x redpen-distribution-*.*.*-SNAPSHOT/conf/
x redpen-distribution-*.*.*-SNAPSHOT/js/
x redpen-distribution-*.*.*-SNAPSHOT/js/test/
x redpen-distribution-*.*.*-SNAPSHOT/lib/
...
....

Now the RedPen package is ready to use.

....
$cd redpen-distribution-*.*.*-SNAPSHOT
$bin/redpen -h
usage: redpen-cli [Options] [<INPUT FILE>]
  -c,--conf <CONF FILE>                Configuration file (REQUIRED)
  -f,--format <FORMAT>                 Input file format
                                       (markdown,plain,wiki,asciidoc,latex)
  -h,--help                            Displays this help information and exits
  -l,--limit <LIMIT NUMBER>            error limit number
  -r,--result-format <RESULT FORMAT>   Output result format
                                       (json,json2,plain,plain2,xml)
  -v,--version                         Displays version information and exits
....

=== Testing

When you modify RedPen source files, please make sure to add the test cases to make the
reviewer understand the expected behaviors. In addition run whole test cases before making the Pull Request.
RedPen test cases are run with the following command.

....
$mvn test
....

