= RedPen Input Formats
:toc: right

RedPen supports three types of input formats ("Plain Text", "Wiki", and "Markdown").

[[plain-text]]
Plain text
----------

Plain text supports a set of paragraphs. Paragraphs are separated by two
new lines. For example, the following article has two paragraphs.

----
This is a first paragraph. This paragraph is the introduction of this article.
It introduces the central issue discussed throughout the rest of the article.

Second paragraph describes the details of the issue and attempts to present a solution.
----

[[asciidoc]]
AsciiDoc
--------

See the http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[AsciiDoctor reference]

[[latex]]
LaTeX
-----

NOTE: RedPen does not supports Macros defined by writers.

[[wiki-format]]
Wiki format
-----------

RedPen supports a subset of Wiki syntax. Currently, the supported
elements of Wiki syntax are as follows.

[[headings]]
Headings
~~~~~~~~

To create a heading, add a line starting with "h[1234]. ". The number after h represents the level of the heading or section.

[[inline-formatting]]
Inline Formatting
~~~~~~~~~~~~~~~~~

RedPen supports the following inline formatting.

[[bold]]
Bold
^^^^

----
**this is a Bold sentence.**
----

[[italic]]
Italic
^^^^^^

----
//this is an italic sentence.//
----

[[unerline]]
Unerline
^^^^^^^^

----
__this is an underlined sentence.__
----

[[strikethrough]]
Strikethrough
^^^^^^^^^^^^^

----
--this is a strikethrough sentence.--
----

[[links]]
Links
~~~~~

Links elements are included in Wiki formatted documents.

[[lists]]
Lists
~~~~~

Wiki syntax supports two types of lists.

[[bulleted-lists]]
Bulleted Lists
^^^^^^^^^^^^^^

To enter a bulleted list, start a line with an asterisk. The number of
asterisks denotes the indent level of the list.

----
* List
* List
** Sub List
----

[[numbered-list]]
Numbered List
^^^^^^^^^^^^^

If you want to add numbered lists, use the hash/pound symbol (#) instead
of the asterisk used by Bulleted Lists.

[[comments]]
Comments
~~~~~~~~

To add a comment to the wiki source, add a [!-- ... --] block. The
following shows a sample comment.

----
[!--
  This is a comment.
--]
----

[[paragraphs]]
Paragraphs
~~~~~~~~~~

Paragraphs are separated by two new lines. This syntax is the same as
for plain text.

[[markdown]]
Markdown
--------

RedPen currently supports the following Markdown elements.

[[headings-1]]
Headings
~~~~~~~~

Two styles of headings are supported.

* Underlined headings

First and second level headings can be specified using underlines.

----
First-level headings
====================
----

----
second-level headings
---------------------
----

* Atx style headings

1-6 hash or pound characters (#) at the beginning of a line.

For example:

----
# First-level heading
## Second-level heading
### Third-level heading
----

[[inline-formatting-1]]
Inline Formatting
~~~~~~~~~~~~~~~~~

RedPen supports the following inline formatting.

[[bold-1]]
Bold
^^^^

Wrap characters with double asterisks or underscores for bold. The
following are samples of bold sentences.

----
**this is a Bold sentence.**
__this is also a Bold sentence.__
----

[[italic-1]]
Italic
^^^^^^

Wrap characters with a single asterisk or underscore for italics. The
following are samples of italic sentences.

----
*this is a italic syntax.*
_this is also a italic syntax._
----

[[links-1]]
Links
~~~~~

To create a link, wrap square brackets around the link's label and
parentheses around the URL. For example.

----
[label](url)
----

[[lists-1]]
Lists
~~~~~

The Markdown parser used by RedPen supports two types of lists -
Bulleted lists and Numbered lists.

[[bulleted-lists-1]]
Bulleted Lists
^^^^^^^^^^^^^^

To create a bulleted list, start a line with an asterisk or a hyphen.
The lists are nested according to how many leading spaces there are. The
following is a example of a bulleted list using asterisks.

----
* List
* List
  * Sub List
  * Sub List
----

[[numbered-list-1]]
Numbered List
^^^^^^^^^^^^^

If you want to create a numbered list, use a number followed by a
period, as in the following example.

----
1. List
2. List
----

[[paragraphs-1]]
Paragraphs
~~~~~~~~~~

Paragraphs are separated by two new lines. This syntax is the same as for plain text.
